### ISSUE TITLE
Input output not working

### ISSUE THREAD

**Issue by AyushBans** [NicoHood/HID#103]
Sir, I am a novice so I'm sorry in advance if it is some stupid mistake. I installed hoodloader 2.0.5 into arduino uno R3 using arduino 1.8.1 . I'm unable to use input output mode when I select board as hoodloader 16u2 and board/bootloader as hoodloader uno( not even improved keyboard example). Although, I can use keyboard.Write under same selections which is working fine(but not digital Read or digital write and also digital.Read and digital.Write are working finewhen using board as hoodloader uno(not 16u2). Also I'm unable to use alt+ shift at a single stroke. please help me in that too if possible

**Comment by NicoHood** [comment]
Please read the HL2 Wiki carefully to understand how it works.

The key press issue might be because you have a different keyboard layout or used the library wrong. See the examples.
