### ISSUE TITLE
Is there a support for horizontal mouse wheel?

### ISSUE THREAD

**Issue by NMHoang05** [NicoHood/HID#106]
Hello!
My current project is to build a hand-wired one-handed keyboard with Arduino Pro Micro and it still has some spare pins and I thought of attaching a joystick to it.

my preference is to use the joystick as mouse wheel scroll, vertically and **horizontally**.
but I don't know if this library support the mouse wheel or should I look elsewhere?

by the way, I'm on Window 10 and horizontal scroll support is horrible. ("non-existence", I may say)

Thank you,
Hoang.

**Comment by NicoHood** [comment]
I dont know if its even technically possible. You might want to give me some reference implementations or look at the usb hid docs.

**Comment by NMHoang05** [comment]
hmm... right now I have not started coding yet (I will reuse code from my previous hand-wired keyboard)

I will search around and I will get back here if I find anything.
