### ISSUE TITLE
Arduino Leonardo Micro (ATMEGA32U4): Keyboard volume does not work on Windows when using Keyboard object instead of Consumer object

### ISSUE THREAD

**Issue by codebeat-nl** [NicoHood/HID#114]
```
if( <buttonpressed> )
 { Keyboard.write( HID_KEYBOARD_VOLUME_DOWN ); }
if( <anotherbuttonpressed> )
 { Keyboard.write( HID_KEYBOARD_VOLUME_UP ); }
delay(10);
.......................
```

It does work on Android but not on Windows. Test it on Windows 7 and Windows 10.  Is there a fix for this?

EDIT:
Okay, found it. I have used the Keyboard object instead of the Consumer object. But it is kinda strange why it is not working when using the Keyboard object. Can you explain why it works with Android and not with Windows or is this an error?

**Comment by NicoHood** [comment]
Its not working on Windows because Windows is Windows.
They did not implement it, like they did with many things.
It should work on Linux and maybe on IOS too.

**Comment by codebeat-nl** [comment]
Yes, is still working when you use the Consumer class instead of the Keyboard class. I don't know what the difference is between them?

**Comment by NicoHood** [comment]
The consumer class is made for such things. Audio, Media keys, browser button etc. Thats the normal way to do it. You can also include it inside a keyboard descriptor, but windows just ignores that. For windows a keyboard only has "normal" keys, no consumer keys. Ask micro$$$$, not me about this issue. You cant get this fixed.
