### ISSUE TITLE
HIP-Project and Arduino IDE 1.83 and DUE

### ISSUE THREAD

**Issue by oxedgar** [NicoHood/HID#116]
Hi i cannot able to use your library in arduino IDE 1.8.3 and with my arduino DUE!
with more troubles, i need to copy manually files PluggableUSB.cpp, PluggableUSB.h and USBAPI.h on folders  HID-APIs, MultiReport and SingleReport. beause each compilation faild with no souch files!

and now i get this compilation error when i compile to my Arduino Due:
\Arduino\libraries\HID-Project\src\HID-APIs\USBAPI.h:25:24: fatal error: avr/eeprom.h: No such file or directory

Have you any issue for this?

**Comment by NicoHood** [comment]
Arduino DUE is not supported.
