### ISSUE TITLE
How to change the device name(HID)

### ISSUE THREAD

**Issue by starock** [NicoHood/HID#125]
I want to make a keyboard with HID porject. And show the device name(Arduino Leonardo) with what I want. Just like "MyKeyboard".

HID-project can do that?

**Comment by BDanAnd** [comment]
I did this by editing the file "(ArduinoIDERootDir)\hardware\arduino\avr\boards.txt". Just copy the description block of Arduino Leonardo, change the "leonardo." prefix to your,  change the "<your_prefix.name" (for Arduino IDE menu) and then change the "usb_product". I checked on the Arduino Micro.

**Comment by starock** [comment]
> I did this by editing the file "(ArduinoIDERootDir)\hardware\arduino\avr\boards.txt". Just copy the description block of Arduino Leonardo, change the "leonardo." prefix to your, change the "<your_prefix>.name" (for Arduino IDE menu) and then change the "usb_product". I checked on the Arduino Micro.

Thank you so much, I did it! hahaha~
