### ISSUE TITLE
Where to define pins to which gamepad buttons are connected

### ISSUE THREAD

**Issue by seanspotatobusiness** [NicoHood/HID#128]
I'd like to make a 12-key macropad using seven pins of an Arduino in a 4x3 matrix. Is that possible using the HID gamepad sketch? I can't see where I'm supposed to define the pins to which the keys/buttons are connected.

**Comment by NicoHood** [comment]
You need to programm it yourself of course and do your own mapping. Check the example. I suggest to ask this question in the arduino forum or in the irc chat again if you need further help with programming.
