### ISSUE TITLE
Non US-Layout's

### ISSUE THREAD

**Issue by acujl** [NicoHood/HID#131]
heya I'm a newbie on arduino.
I just want to make a duckino that works with portuguese layout and it's hard to implement non-US layouts since I never saw a tutorial on that, can you help me with that?

Hope to see a easy way to change layouts

**Comment by NicoHood** [comment]
See https://github.com/NicoHood/HID/issues/22

**Comment by acujl** [comment]
Already saw..

**Comment by NicoHood** [comment]
No there is no way available and if you do not understand the thread, there is no good chance for you to have different keyboard layout support in the near future. I suggest using a teensy then, as paul implemented it for the teensy core.
