### ISSUE TITLE
Gamepad example not picking up button press

### ISSUE THREAD

**Issue by EnthusedDragon** [NicoHood/HID#144]
Hey,

I've got a button wired to my Arduino UNO to pin 2 and ground.

I'm busy wiring a old game controller as a Gamepad.

The button press registers in the 328 but not on the 16u2 where the gamepad script gets uploaded to.

Am I supposed to upload something onto the 328 that communicates back to the 16u2?

This while process has been next level for me.

Thanks in advance.

**Comment by NicoHood** [comment]
Sure you need some kind of communication on both MCUs.
https://github.com/NicoHood/HoodLoader2/tree/master/avr/examples/HID-Bridge
