### ISSUE TITLE
Getting no input on Windows 10

### ISSUE THREAD

**Issue by Greg-J** [NicoHood/HID#158]
I followed the instructions using an uno to program another (two others, actually) with HoodLoader 2 16u2, but I'm having no luck.

I loaded up the Advanced Keyboard sketch and when the Uno restarts it does show up as a keyboard in devices, but when I put pin 2 to gnd, nothing happens.

I then loaded up the Gamepad sketch and when it restarts, Windows see's it as a gamepad called HoodLoader2 16u2. So it would seem that it is being programmed correctly. However, nothing happens when I put pin 2 to ground. The sketch makes it look like it will go through a bunch of random button presses, but nothing happens.

I have tried this on both of the Unos that I installed HoodLoader onto and both of them behave the same way. The only difference being that one of them has the LED flash (that was the last sketch I had on it) and one of them doesn't have the LED flash.

Any ideas as to what I'm doing wrong?

---

EDIT:

From searching around, it looks like I have to write two different sketches and have them talk to eachother somehow, but there doesn't seem to be any example on how to do this. I'm confused as to why go through the trouble of allowing people with Unos to do this only to not provide a real example on how to turn button presses into HID input?

Maybe I just don't get this at all. I would super appreciate the help though. I'm trying to repurpose an old arcade cabinet with the stuff I have lying around and I feel like I'm getting there, but I'm currently at an impasse.

**Comment by NicoHood** [comment]
You have to use the pins of the 16u2, not the 328. Checkout the hoodloader2 wiki.

Communication between the two MCU is up to you, as complicated as you wish. Nobody said it will be easy. It is an additional nice feature, but not perfect for all use cases. You might better you an arduino micro if you want to have usb support with IO etc.
