### ISSUE TITLE
Teensy 2.0 supported?  What is TeensyKeyboard?

### ISSUE THREAD

**Issue by sofakng** [NicoHood/HID#162]
I'm a little confused on using this library with a Teensy 2.0 board.

Can I use this library with all its features (Improved Mouse, Absolutely Mouse, etc) with this board?  I'm confused because the Teensy's Mouse library says it doesn't support absolute position on Teensy 2.0 (but works on Teensy 3.0+ I think).

I'm also confused because this library has something called "TeensyKeyboard".  Do I need this support, or why would I want it?

**Comment by NicoHood** [comment]
Teensy is not supported, the code is old.
