### ISSUE TITLE
Mouse Abs + System only works under special circumstances?

### ISSUE THREAD

**Issue by sofakng** [NicoHood/HID#163]
The documentation for this project mentions the following:
- Mouse Abs only works with system report under special circumstances.

Can you explain a bit more about this?  I'd like to use Improved Keyboard + Mouse Abs + System (and maybe Serial?) if possible with my Teensy 2.0.

**Comment by NicoHood** [comment]
Teensy is not supported. Sometimes it works good on windows, sometimes not. Thats all.

**Comment by xcarcelle** [comment]
I did some tests w/ the master branch with Arduino Micro and the absoluteMouse example but no success with Android nor iOS, have you heard of successful absolute mouse with Android/iOS ? Cheers.
