### ISSUE TITLE
Multiple Gamepads

### ISSUE THREAD

**Issue by lcriscola** [NicoHood/HID#171]
I am using a mega and uploading a small sktech to the 16u2 chip.
I see that the library has a Gamepad, Gamepad1, Gamepad2, Gamepad3, Gamepad4 variables that we can use. Is this supposed to be used so we can have up to five joysticks? I am using all five variables at the same time, but Windows only see one Joystick.

Is it even possible to have more than one joystick?

I found your bootloader from a link in https://github.com/MHeironimus/ArduinoJoystickLibrary/wiki/Supported-Boards
But that library doesn't seem to work with this boot loader mod.

Thanks for your great work.

**Comment by NicoHood** [comment]
The 16u2 has not enough endpoints to support all of them. Gamepad is a multireport gamepad, the others with numbers are single report gamepads that use an usb endpoint each. You can read more about this in the wiki. Please use a 32u4 or less gamepads.
