### ISSUE TITLE
How to use USB mouse control

### ISSUE THREAD

**Issue by kenny196** [NicoHood/HID#178]
Hi All,
I have tried to flash ImprovedMouse.ino into my micro pro 32u4  to use as a mouse to control a computer  but it seem not working at all.

**Comment by NicoHood** [comment]
Which os did you use, do the other examples work?

**Comment by kenny196** [comment]
I am trying to do the arduino mouse kvm code that you presented.
I am having problems compiling and running on visual studio codes.

So i took the keyboard pass thru code and then added this mouse control to it.
connected the pins 2,3,4
i can pass through the keyboard, but mouse no. not possilble

**Comment by NicoHood** [comment]
Try the mouse separately or maybe ask in the arduino forum/irc chat for help.
