### ISSUE TITLE
Pro Micro (32U4) is after first flash unflashable

### ISSUE THREAD

**Issue by Devilscave** [NicoHood/HID#184]
Hey,
I have a big problem,
I have used your library and wanted to program a keyboard button function, so far everything OK.
So Arduino connected, IDE set, device -> Com 22, first flashed everything OK, but device resets and logs in now under Com23 but still as Arduino Micro.
But now I want to flash again, Combine the Arduino IDE and start uploading the sketch, you hear the Windows USB unplug sound, all the LEDs on the Arduino are flashing but he does not answer, I have to disconnect him completely and reconnect. Then he has Com23 again but it's the same problem. When trying to flash it, he logs out completely and not new one. So I can not flash an Arduino 2 times or more. What must i do?

I use:
Arduino IDE 1.8.9
Win7 64x
HID Project 2.6.1

**Comment by NicoHood** [comment]
Depending on the installed bootloader, you must run the bootloader again. I guess the sketch you uploaded has a problem, thatswhy the bootloader autoreset does not work.
