### ISSUE TITLE
Update the Copyright info

### ISSUE THREAD

**Issue by MRNIU** [NicoHood/HID#216]
I noticed that the copyright information was not updated:
`See the readme for credit to other people.`
But the information is actually here: [Useful-Links-Credits](https://github.com/NicoHood/HID/wiki/Useful-Links-Credits).
Can I replace this sentence with `See the wiki/Useful-Links-Credits for credit to other people.`?

**Comment by NicoHood** [comment]
See my comment on the linked arduino PR
