### ISSUE TITLE
Cannot send HID report without REPORT_ID

### ISSUE THREAD

**Issue by wbovela** [NicoHood/HID#223]
Hi,

How do I send a HID Report without REPORT_ID. HID.SendReport() requires an id as first parameter. This requires a Report_Id (0x85) to be present in the descriptor.

Thanks!

**Comment by gdsports** [comment]
Use the Single* classes. For example, SingleConsumer versus Consumer.

**Comment by wbovela** [comment]
> Use the Single* classes. For example, SingleConsumer versus Consumer.

Thanks. That was a good tip. I was able to use the GamePad code to employ the USB.SendReport() call without a REPORT_ID. It was exactly what I was trying to do, except it hasn't solved the problem I was hoping to fix :)
