### ISSUE TITLE
Gamepad API went?

### ISSUE THREAD

**Issue by MrDannyPicard** [NicoHood/HID#227]
I am having a hard time understanding how to use the Gamepad feature.

Can i use the same argument as when i use joystick.h on my leonardo?

If not, what are the necessarys i need to make it work as a gamepad input went grounding pin3?

**Comment by NicoHood** [comment]
Please checkout the examples or ask further questions in the arduino forum.

**Comment by MrDannyPicard** [comment]
I did check the example but they all link to the gamepad api wiki page, which is in a TODO list. Not very useful.

And i don't know if a modded HID library is a good thing to ask about in the arduino forum, they all going to say to just use a leonardo or the like. I've searched before asking here.

All i want to know is if there's difference between the joystick.h "official library" and this one in term of argument.

**Comment by NicoHood** [comment]
This library is not "modded". You could not know, but the Arduino team decided to keep their libraries simple, and leave the complex stuff to me. That was quite some years ago.

The docs are incomplete - sorry about that. The example should be quite self explaining however. The difference between the joystick and the gamepad is, that is has mor buttons and axis. Most users need those buttons. And you can use a Gamepad as single or multireport device and you can have multiple gamepads together. Checkout the wiki about single and multireports, if that is new to you.
