### ISSUE TITLE
Looking to use an HC-05 module on master with an HID bluetooth device

### ISSUE THREAD

**Issue by lucasdellabella** [NicoHood/HID#240]
I'm very new to all of this, can I use this library to interpret the serial data from my hc-05 module as HID? Or do I have to have the HC-05 module interpret the data sent via bluetooth as HID in the HC-05's firmware?

**Comment by NicoHood** [comment]
If you want to emulate a bluetooth keyboard with your arduino then this has nothing to do with this library. I remember that it is also not possible with the limited function of the HC-05, but I've tested that ~7 years ago, so thinks might have changed, I dont know.

Anyways: Please ask such questions in the arduino forum or via email. This is a bugtracker and not a support forum.
