### ISSUE TITLE
 What we have keyboard in Spanish we need help

### ISSUE THREAD

**Issue by xm00ds** [NicoHood/HID#247]
reviewing I got that the design of the program was thought to create new keyboard templates, but it is not clear how I should map for keyboard in Spanish, I need help with the keyboard mapping in Spanish because the correct execution of the scripts depends on it. You will explain with dellate how we can edit the ImprovedKeylayoutsXX file for keyboard in Spanish

**Comment by SukkoPera** [comment]
Please see #261, read the notes carefully. It would be great if you could help with the testing, there's an example that makes that very easy.
