### ISSUE TITLE
NicoHood HID bricked my device

### ISSUE THREAD

**Issue by x1unix** [NicoHood/HID#271]
Hello, I have an Arduino Pro Micro and I tried to flash a simple sketch and use NicoHood's HID library.

Device doesn't recognized in any system (Linux/Win) and all systems complain for USB device descriptor.

Some dmesg sample:
```
device descriptor read/64. error -71
```

Thanks to SparkFun, they included some kind of recovery mode on a board so I was able to revive my board quickly.
Please add some kind of disclaimer about possibility of corrupted USB device descriptor (other issues).

**Comment by x1unix** [comment]
**Update:** looks like builtin `Keyboard.h` from arduino did some mess when it was liked with HID library.

**Comment by antoniomolram** [comment]
did you figure out how to fix this? I am having a similar issue

**Comment by x1unix** [comment]
@antoniomolram I had both imported Arduino's standard keyboard library and NicoHood's libraries.

The solution was to remove Arduino Keyboard library from a project and reflash my project to Arduino board.

I've used SparkFun's Arduino Pro Micro which had some kind of recovery mode, which allows to delay sketch execution for a couple of seconds, which allowed me to reflash my sketch.
