### ISSUE TITLE
Media not work on Android

### ISSUE THREAD

**Issue by MaximDroy** [NicoHood/HID#3]
Hi. I have used the Media function with your firmware. I want MEDIA_VOLUME_UP and MEDIA_VOLUME_DOWN. Everything works goods on PC (Windows, MAC etc.). But on the Android it won't. Android see the Arduino as a Keyboard but Media functions not work.

**Comment by MaximDroy** [comment]
I'm sorry but I'm really can't understand your instruction about HoodLoader 2 and HID. So intrecately. Can you make step by step instruction? I have UNO R3. With images or youtube video.

Early I just upload hex with FLIP. Now I can't do that :)

**Comment by NicoHood** [comment]
I recommend you to start with a clean install of ide 1.6 rc1. Try the new version, it is step by step. Make sure to use the right branch. I will merge this to the master in the next weeks.

https://github.com/NicoHood/HID/tree/Official-Integration
https://github.com/NicoHood/HoodLoader2/tree/dev

For any further question ask via mail or chat:
https://nicohood.wordpress.com/about/

**Comment by NicoHood** [comment]
Fixed in the dev branch
