### ISSUE TITLE
BootKeyboard.getLeds() only works with Keyboard Viewer Enabled on MacBook Pro

### ISSUE THREAD

**Issue by shuangg** [NicoHood/HID#319]
I am using BootKeyboard.getLeds() with Leonardo/Micro to detect Cap Lock status on a MacBook Pro but it only works with Keyboard Viewer enabled.

**Comment by NicoHood** [comment]
What is a keyboard viewer?

**Comment by shuangg** [comment]
It is the onscreen keyboard also called Accessibility Keyboard. https://support.apple.com/en-gb/guide/mac-help/mchlc74c1c9f/mac

**Comment by shuangg** [comment]
@NicoHood It seems Mac only broadcasts caps lock status to all keyboards when the onscreen keyboard is enabled.

**Comment by NicoHood** [comment]
Thanks for the feedback
