### ISSUE TITLE
Broken link in Wiki

### ISSUE THREAD

**Issue by ZeroOne010101** [NicoHood/HID#371]
The link "https://github.com/NicoHood/HID/wiki/HID-Bridge-%28HL2%29" present on [this site](https://github.com/NicoHood/HID/wiki/Troubleshoot-FAQ) just leads to the main wiki page.

**Comment by NicoHood** [comment]
Where in the wiki did you find that link?

**Comment by ZeroOne010101** [comment]
In the Troubleshoot-FAQ, section "custom-firmwares"

https://github.com/NicoHood/HID/wiki/Troubleshoot-FAQ#custom-firmwares

**Comment by NicoHood** [comment]
Thanks, I've corrected that part it seemed very old and confusing written.
