### ISSUE TITLE
HID-PROJECT

### ISSUE THREAD

**Issue by Ajay-Sharitra** [NicoHood/HID#375]
In file included from E:\EH\Aurdino Uno R3 2 Rubber Ducky\Sample Payload\Prank\sketch_sep01a\sketch_sep01a\sketch_sep01a.ino:1:0:
C:\Users\User\Documents\Arduino\libraries\HID_Project-2.8.2\src/HID-Project.h:35:2: error: #error HID Project can only be used with an USB MCU.
 #error HID Project can only be used with an USB MCU.
  ^~~~~
Multiple libraries were found for "HID-Project.h"
 Used: C:\Users\User\Documents\Arduino\libraries\HID_Project-2.8.2
 Not used: C:\Users\User\Documents\Arduino\libraries\HID-master
exit status 1
Error compiling for board Arduino Uno.

This is the error I am getting every time I am trying compile an Ducky Script into an Arduino File.
What is this error? And can someone please help me how to fix this?
 👍

**Comment by hlcmOxO** [comment]
arduino uno r3 does not support usb hid
