### ISSUE TITLE
send wrong key for enter as "("

### ISSUE THREAD

**Issue by vincentgao-ca** [NicoHood/HID#377]
Keyboard.write( KEY_ENTER);
BootKeyboard.write( KEY_ENTER);
 I use Arduino 1.8.19, HID 2.8.2

I tested many times, and saw all the issues, no way to solve this.
Before I changed to nicohood hid library, everything is ok, but after I changed to NicoHood HID, the host receives "(", instead of ENTER. For the other keys, it works well.
Also I used it use Surface UEFI keyboard, not working at all, the Surface UEFI not working but it works well when plugging a real keyboard.

Please give a solution for how to use ENTER key and how to support Surface UEFI. Thanks.

**Comment by NicoHood** [comment]
Hi,
which keyboard layout do you use?

**Comment by vincentgao-ca** [comment]
Hi NicoHood,
I use  US_ENGLISH, Sparkfun Pro micro, 32u4 nano. I am trying to fix this issue now. I used Keyboard.write(KEY_ENTER) it is correct, I can't use uint8_t as input, the host will get "(".
For UEFI, still not working, either Keyboard or BootKeyboard class functions.
Thank you for your reply so quickly.
vincent

**Comment by NicoHood** [comment]
I have no idea what is going wrong

**Comment by vincentgao-ca** [comment]
I have to translate all the virtual code into Arduino code, especially for control, alt, Fn keys.
About supporting the UEFI keyboard, do you have any idea for solving the issue? Thank you.

**Comment by vincentgao-ca** [comment]
I finally made it, translate each virtual key to the defined keys ascii map. 
Thank you.
