### ISSUE TITLE
Board manager with IDE 1.6.4 warnings

### ISSUE THREAD

**Issue by pierrotm777** [NicoHood/HID#40]
The board manager return me some warnings !
Warning: platform.txt from core 'HID Project USB-Core' contains deprecated tools.avrdude.cmd.path={runtime.ide.path}/hardware/tools/avr/bin/avrdude, automatically converted to tools.avrdude.cmd.path={path}/bin/avrdude. Consider upgrading this core.
Warning: platform.txt from core 'HID Project USB-Core' contains deprecated tools.avrdude.config.path={runtime.ide.path}/hardware/tools/avr/etc/avrdude.conf, automatically converted to tools.avrdude.config.path={path}/etc/avrdude.conf. Consider upgrading this core.
Warning: platform.txt from core 'HID Project USB-Core' misses property tools.avrdude.path, automatically set to {runtime.tools.avrdude.path}. Consider upgrading this core.

**Comment by NicoHood** [comment]
Fixed in the dev branch already.

Thanks for the report anyways ;)

**Comment by NicoHood** [comment]
IDE 1.6.6 can be tested now. Those setting dont matter then at all.
https://github.com/NicoHood/HID/tree/dev_2_4
