### ISSUE TITLE
#pragma message "Using default ASCII layout for keyboard modules"

### ISSUE THREAD

**Issue by CasperHxR47** [NicoHood/HID#403]
Hello all,

I can't figure this out. I keep getting these errors concerning something about keyboard type and the resulting message is 'using default layout', which sounds fine, but I'm unable to compile. 

I've tried to install the latest HID-Project.h version using github and also through the Arduino IDE 2.0.3 Library Manager. 
In the screenshot below I've installed the latest version using github to download the zip file, and installed it by selecting 'sketch' > 'Include Library' > 'Add .Zip Library'. 

At the top of my sketch I add:
#define HID_CUSTOM_LAYOUT
#define LAYOUT_US_ENGLISH

#include "HID-Project.h"
#include "HID-Settings.h"

(I've also tried is as #include <HID-Project.h>, but that doesn't seem to make a difference...)

However, I still get errors. Assistance would be greatly appreciated!

![Capture](https://user-images.githubusercontent.com/66280740/215970531-7c98ac83-41d1-4d25-85fa-9590aa6f0f97.PNG)

**Comment by NicoHood** [comment]
This is not an error, this is an informative message.
