### ISSUE TITLE
PID and VID Configuration

### ISSUE THREAD

**Issue by petersonsenha** [NicoHood/HID#41]
(Sorry for my english, i'm student brazilian)
"My engeneering project: Arduino working like "HP Printer" and filtering data."
Hi, how to configure vid and pid of the MEGA16u2?
I've set HoodLoader2 and HDI project and both works ok,
I picked the "pid and vid" of Photosmart c4600 series (http://hplipopensource.com/hplip-web/models/photosmart/photosmart_c4600_series.html) and wanted to copy for my arduino.

Could me help to setup pid and vid of MEGA16u2?
(USB VID:PID	1008:29713)

Thanks!

**Comment by NicoHood** [comment]
https://github.com/NicoHood/HoodLoader2/blob/master/avr/boards.txt#L46
https://github.com/NicoHood/HoodLoader2/blob/master/avr/boards.txt#L56

Please do not open Issues to ask questions.
Contact me via my contact address. Always go to www.nicohood.de to get my latest website.
