### ISSUE TITLE
HID descriptor limited to 255 bytes

### ISSUE THREAD

**Issue by dfleck** [NicoHood/HID#42]
In USBCore.h
#define D_HIDREPORT(_descriptorLength) \
	{ 9, 0x21, 0x1, 0x1, 0, 1, 0x22, _descriptorLength, 0 }

should be

#define D_HIDREPORT(_descriptorLength) \
	{ 9, 0x21, 0x1, 0x1, 0, 1, 0x22, _descriptorLength, _descriptorLength>>8 }

**Comment by NicoHood** [comment]
Thanks, will check that out!

**Comment by NicoHood** [comment]
Fixed in IDE 1.6.6

I will stop the work on the patched HID-Core and switch back to a library only.
So this patch never got included here in this project (maybe dev, dont remember) but after the change it will work anyways with the new IDE.
