### ISSUE TITLE
Gamepad (Arduino UNO clone with 16u4)

### ISSUE THREAD

**Issue by MatyasKrabica** [NicoHood/HID#440]
Hello, I'm using an arduino uno clone with a 16u4 microchip + a large 328P (hope you understand me) What do I have to do to get the gamepad working? (I need 4x axis for the steering wheel)

**Comment by matysek66055** [comment]
hi, i installed hoodloader v2, and all, but when i upload gamepad code (arduino switch to gamepad) but idk why i cant use A0 for axis Z or someting else (not just a0 but all analog pins) its says A0 is not declared in scope.
