### ISSUE TITLE
Gamepad control signals from host

### ISSUE THREAD

**Issue by AGausmann** [NicoHood/HID#52]
My robotics group and I are making a custom driver's console that has a 4x4 button matrix with RGB LEDs per button. I'm working on implementing an Arduino to act as a game controller, with HID/HoodLoader2 as the backend. I'm looking for a way to read signals from our robot to run the LEDs: our robot library has a [`setOutput(int, boolean)`](http://team2168.org/javadoc/edu/wpi/first/wpilibj/Joystick.html#setOutput-int-boolean-) that allows us to send the signals, but I can't find a way to receive them.

**Comment by NicoHood** [comment]
I dont understand what you want to know from me. I also dont know what is behind the setOutput and what your hardware setup looks like.

If you use HL2 both MCUs are connected via Serial and you have to do your own bridge. See the wiki for an example.

Also this is not a support forum. Contact me via mail, I wont respond here again.
http://www.nicohood.de
