### ISSUE TITLE
Add different HID's sublibraries to Arduino Library Manager

### ISSUE THREAD

**Issue by q2dg** [NicoHood/HID#56]
Keyboard and Mouse already are official and default installed in Arduino's IDE, but your Gamepad library (for instance, but other ones too) would be a nice addition to be found in the Library Manager.
Thanks

**Comment by NicoHood** [comment]
Its already available in the dev branch. But since 1.6.6 isn not out there and the Pluggable USB API is not 100% fix yet I will not publish this to the library manager.

**Comment by q2dg** [comment]
Ok, thanks
