### ISSUE TITLE
1) how to wire PC keyboards to Arduino? 2) Arduino Due USB host suported?

### ISSUE THREAD

**Issue by VogonJeltz** [NicoHood/HID#57]
hey,
2 short questions:
1) how to wire PC keyboards (USB? PS/2 ?)  to Arduino? 
2) is Arduino Due USB host port suported? (just see a avr subfolder, no arm subfolder)

**Comment by NicoHood** [comment]
1) Read the wiki/official docs. Via micro USB. PS2 is a whole different story. Your arduino acts as USB keyboard, this has nothing to do with PS2

2) Nope. And maybe never will. a) the sam API might differ and b) is not implemented yet. There is currently a lot of work going on with USB and the official Arduino project. I dont need sam, so I wont implement it if it takes too much time. I also cannot test the code. Feel free to open a PR with a working patch.

3) Next time contact me via PGP mail: www.nicohood.de All questions will be answered, further github issues will be ignored. This is not a support forum, sorry.
