### ISSUE TITLE
Compilation Error: fatal error: Platform.h: No such file or directory  #include "Platform.h"

### ISSUE THREAD

**Issue by WillsB3** [NicoHood/HID#6]
I get this error when trying to upload the Gamepad project example to my Micro:

```
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/HID.cpp:140:22: fatal error: Platform.h: No such file or directory
 #include "Platform.h"
                      ^
compilation terminated.
Error compiling.
```

I'm using Arduino 1.5.8 Beta on OSX, and I moved the HID Library's *.h and *.cpp files to `/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/` replacing the ones that were there (as per the install instructions in this projects readme.)

I've checked in `/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/` but there does not appear to be a Platform.h.

I'm using the 1.8 release of the HID library.

Any ideas?

**Comment by sxj731533730** [comment]
canning dependencies of target ncnn2mem
[ 55%] Building CXX object tools/CMakeFiles/ncnn2mem.dir/ncnn2mem.cpp.o
[ 55%] Linking CXX executable ncnn2mem
[ 55%] Built target ncnn2mem
Scanning dependencies of target ncnnoptimize
[ 56%] Building CXX object tools/CMakeFiles/ncnnoptimize.dir/ncnnoptimize.cpp.o
[ 56%] Linking CXX executable ncnnoptimize
[ 56%] Built target ncnnoptimize
tools/caffe/CMakeFiles/caffe2ncnn.dir/build.make:80: *** target pattern contains no `%'.  Stop.
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] Error 2
make: *** [all] Error 2


我遇到这个问题 是不是protobuf 有版本要求呢  ？ 一脸懵逼
