### ISSUE TITLE
HID too big for 8u2?

### ISSUE THREAD

**Issue by flupes** [NicoHood/HID#62]
Thanks to your project, I was really excited to try giving a new life to an old Uno-328 with a mega8u2.
I looks however that I cannot fit the code on the tiny 8u2 (I am using dev_2_4 rolled back to #357baf2)

Is there an option for a "lite" version (looks like 1.7 had something)? I am doing something really wrong (I am worried about the 2 versions of the HID listed)?

Partial build log:
```
Arduino: 1.6.6 Hourly Build 2015/10/29 11:41 (Windows 7), Board: "HoodLoader2 8u2, HoodLoader2 Uno"

[ removed] 
Using library HID-project at version 2.4 in folder: C:\Users\flupes\devel\arduino\libraries\HID-project 
Using library HID at version 1.0 in folder: R:\Arduino\arduino-nightly\hardware\arduino\avr\libraries\HID 

Sketch uses 5,394 bytes (131%) of program storage space. Maximum is 4,096 bytes.
Global variables use 157 bytes (30%) of dynamic memory, leaving 355 bytes for local variables. Maximum is 512 bytes.
processing.app.debug.RunnerException: Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
	at cc.arduino.Compiler.size(Compiler.java:312)
	at cc.arduino.Compiler.build(Compiler.java:153)
	at processing.app.Sketch.build(Sketch.java:1108)
	at processing.app.Sketch.build(Sketch.java:1083)
	at processing.app.Editor$BuildHandler.run(Editor.java:2011)
	at java.lang.Thread.run(Thread.java:745)
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
```

**Comment by NicoHood** [comment]
Well in this case there is no way. Normally the UNO R3 have a 16u2 which is quite good.

The 8u2 is somehow more limited in flash. The bootloader takes 4/8kb. And the usb Core itself is around 4kb.

So for the nearer future there are only a few things that could work:
* Dont use USB at all (deactivation support is pending via a PR in the Arduino Project).
* Deactivate CDC Serial (needs to be patched in the Arduino core, will be a bit more complex, isnt done yet, maybe you can do this?).
* Use a LUFA project (without the IDE) which are in general more stable/advanced, but you dont have the Arduino IDE and its libraries.
* Dont use a bootloader and burn via ISP directly (might not be what you want for debugging etc.)

I'd go for Serial deactivation. I dont have the time to, but some people really would like to see this.

**Comment by flupes** [comment]
Thanks for providing these possible options!
I may look into the CDC Serial, but I am not sure it is worth the effort since it seems I have a very unique case due to this very old board (it is an official Uno first revision).
