### ISSUE TITLE
NKROKeyboard example needs updates to be able to compile

### ISSUE THREAD

**Issue by obra** [NicoHood/HID#64]
It looks like the NKROKeyboard API has been updated significantly since the example code was last touched. 

I _think_ addKeyToReport should just be 'ass'. But I can't for the life of me figure out what "send_now" should become. It looks like it should be 'send', but that's unimplemented.

**Comment by NicoHood** [comment]
What are you talking about? Whats the bug, I dont understand?

**Comment by obra** [comment]
The NKROKeyboard example code does not compile. It uses an api that no longer exists.

**Comment by obra** [comment]
Tested locally. The issue in question has been resolved, but I've hit another bug. I'll open a new ticket.
