### ISSUE TITLE
How can I read the system's date/time?

### ISSUE THREAD

**Issue by clarkewd** [NicoHood/HID#70]
Thanks for this awesome library. I would like to program the Arduino so that when a button is pressed it "types out" the current date / time. I was hoping to be able to get the date / time from the HID connection - so that the system's current time could be used - preventing the need for a RTC or manual syncing, etc. 

Is this possible? If not, is it a limitation of HID devices ( maybe system does not share time info with them )? Or can you point me in the right direction for doing more research on this? Thanks!

**Comment by NicoHood** [comment]
You better ask this in the arduino forum/chat or via mail/tox chat to me directly. This is not a support forum, sorry.
