### ISSUE TITLE
MPU6050 Accelerometer and Hootloader 2 16u2

### ISSUE THREAD

**Issue by qwertypoluyt** [NicoHood/HID#74]
Since the mouse library doesnt work on arduino uno i had to install Hootloader 2 & HID-Project Library for my solution to work but after installing both of those now I am having problem loading the MPU6050.h, wire.h, I2CDEV.h and other libraries that worked on arduino uno.

I am trying to make the accelerometer MPU6050 to move the cursor of my computer but the thing is the library which I need does not function on Hootloader 2 which i thought it would.

this is the error I get

================

/Users/qwertypoluyt/Downloads/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/Wire.cpp: In member function 'void TwoWire::setClock(uint32_t)':
/Users/qwertypoluyt/Downloads/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/Wire.cpp:87:3: error: 'TWBR' was not declared in this scope
   TWBR = ((F_CPU / frequency) - 16) / 2;
   ^
exit status 1
Error compiling.

================

Please help.

**Comment by NicoHood** [comment]
This is not a support forum.
Please contact me via www.nicohood.de and I am happy to answer your question.
