### ISSUE TITLE
Absolute Mouse on this project not support android

### ISSUE THREAD

**Issue by porchesi** [NicoHood/HID#75]
I try to use with android but it don't has respond and look like it crash.

**Comment by NicoHood** [comment]
It is possible that android does not support absolute mouse.
If you have a teensy, try this instead. If the teensy works, it is an implementation bug. If it does not, its an android limitation.

What android do you mean? For a desktop PC like remix os or a smartphone?

**Comment by porchesi** [comment]
Yes, it is remix os with official remix android box. I don't have teensy hardware. Now, I try to use ImproveกMouse example for make it function same absoluteMouse.

Thank you for suggestion.
