### ISSUE TITLE
Windows 10 insider rawhid performance

### ISSUE THREAD

**Issue by rjonkman** [NicoHood/HID#84]
This is probably not the best place to ask, but has anyone had issues with lagged rawhid performance on   Windows Inside version > 14342?  I don't actually use this library, but I'm experiencing issues on machines running the insider preview, and not on the regular Window's machines.

**Comment by rjonkman** [comment]
I guess that's a no.  I'm seeing issues with my Teensy based products and I thought I'd give you the heads up.

**Comment by NicoHood** [comment]
I do not use windows and I also do not use rawhid that much. And sorry, this is not a support forum, but you can ask via mail.
