### ISSUE TITLE
NKRO Keyboard with modifiers in Array

### ISSUE THREAD

**Issue by SynonZelra** [NicoHood/HID#85]
Hi.
I'm trying to build a NKRO keyboard with atmega32u4 and not sure if it's my own problem here:

First I tried single values like:
`  if (!digitalRead(ctrl))
  {NKROKeyboard.add(KEY_LEFT_CTRL);}
  else
  {NKROKeyboard.release(KEY_LEFT_CTRL);}
  NKROKeyboard.send();`
This works perfect.

Then I tried in array like:
`unsigned key[]={KEY_LEFT_CTRL};
...
  if (!digitalRead(ctrl))
  {NKROKeyboard.add(key[0];}
  else
  {NKROKeyboard.release(key[0]);}
  NKROKeyboard.send();`
The CTRL is not working. but if key[]='a', it types a correctly.

so I wonder if there's the variant error, I replace it with the hex value found on arduino.cc
> Key	Hexadecimal value
> KEY_LEFT_CTRL 	0x80	
still not working.

can you pls. suggest the problem?
thanks

btw. I tried other modifiers with array found it prints the wrong letter.

**Comment by NicoHood** [comment]
Because those names are not integers, those are enums
You'd need to define an enum array.
https://github.com/NicoHood/HID/blob/master/src/HID-APIs/ImprovedKeylayouts.h#L32
