### ISSUE TITLE
Consumer .press and .write

### ISSUE THREAD

**Issue by SynonZelra** [NicoHood/HID#86]
Hi
Just tried consumerAPI to work as multimedia control, the code is really nothing special:

>   if (!digitalRead(pn))
  {Consumer.write(MEDIA_VOLUME_MUTE);}

which works good, and without debouncing, it's really fast.
but when I change to .press:

>   if (!digitalRead(pn))
  {Consumer.press(MEDIA_VOLUME_MUTE);}
  else
  {Consumer.release(MEDIA_VOLUME_MUTE);}

it's not working every time, but more like a random hit.

thanks

**Comment by NicoHood** [comment]
I think your code is of bad structure like this. You press the keys too often, the bus is flooded. You'd need to show the whole code. I suggest asking in the arduino irc or forum for more help.
