### ISSUE TITLE
HID Project can only be used with an USB MCU.

### ISSUE THREAD

**Issue by JamesTheCoder** [NicoHood/HID#87]
I get this error when I attempt to upload any sketches to my device. Looking through previous issues of this doesn't seem to have helped me at all.

I'm using an unofficial Uno that I have successfully flashed HL2 to.

Thanks
James

**Comment by NicoHood** [comment]
You need to select the Hoodloader2 16u2 board. Read the HL2 wiki again please.

**Comment by JamesTheCoder** [comment]
Ahh, sorry about that, I must've missed it. I'll try it in the morning, but I'm sure my idiocy is to blame as usual ;).

**Comment by SachinSAgrawal** [comment]
How do I select the Hoodloader2 16u2 board? I understand I have to short the reset pin twice, but I do not know how to do that. Is there a picture or diagram?
