### ISSUE TITLE
Gamepad example not uploading correctly?

### ISSUE THREAD

**Issue by swoobie** [NicoHood/HID#88]
Hey NicoHood,
I'm having trouble getting Windows 10 to recognize any input using the Gamepad example.
I'm running an Arduino Uno with a 16u2 and Hoodloader 2. I've uploaded the Gamepad example sketch and the Uno shows up in the devices menu as seen in the following:
![image](https://cloud.githubusercontent.com/assets/9885354/17868131/b843067a-686a-11e6-8551-5bcbf7f38e56.png)

I'm not entirely sure the sketch is being uploaded though. I can't see any input in the device's test panel and when I upload the sketch sometimes it takes 3 to 5 tries before I can get past a "avrdude: ser_open(): can't open device "\\.\COM11": Access is denied." or a "Port busy" error.  When it does upload, the device disconnects, changes the com, and immediately says done uploading.
Is that normal behavior when uploading a sketch to the 16u2?

**Comment by dragonet80** [comment]
Where is the button tied to? Ground or Vcc?

**Comment by NicoHood** [comment]
Yes this is the normal upload behavior. I've seen you added me in tox, just ask there other questions ;)
