### ISSUE TITLE
Selected board depends on 'HID' core (not installed)

### ISSUE THREAD

**Issue by Snower4344** [NicoHood/HID#9]
Hi Sir,
I use your [Arduino HID Project 2.1] on the Leonardo board.
But I can not upload the program.
It always alert "Selected board depends on 'HID' core (not installed)"

Please see the picture. Thank you very much

  
![pic](https://cloud.githubusercontent.com/assets/10543166/5753858/1aa702de-9ccb-11e4-8522-a17b07b69618.png)

**Comment by NicoHood** [comment]
Ensure that you rename the HID-master correct to HID. You can also see the note/pic in the readme:
https://github.com/NicoHood/HID/tree/Official-Integration#3-install-the-hid-core-files

**Comment by Snower4344** [comment]
Hi sir,
But I can not find the folder[HID-master] in your HID-Official-Integration.zip file
I unzip the HID-Official-Integration.zip and copy all files to "C:\Program Files (x86)\Arduino\hardware\arduino" .

**Comment by NicoHood** [comment]
And that is wrong. Read the readme again. You have to copy it into the sketchbook and not into your arduino folder.

**Comment by petersonsenha** [comment]
"Error 404, This is not the web page you are looking for"
https://github.com/NicoHood/HID/tree/Official-Integration#3-install-the-hid-core-files

Thanks.

**Comment by petersonsenha** [comment]
where I find HID-Official-Integration.zip ? 
Thanks!

**Comment by NicoHood** [comment]
This is outdated.
Look at the wiki how to install:
https://github.com/NicoHood/HID/wiki/Installation

**Comment by petersonsenha** [comment]
Thanks Nico!
