### ISSUE TITLE
Receive REPORT on device

### ISSUE THREAD

**Issue by exander77** [NicoHood/HID#93]
Is it possible to receive report sent from os to the device?

Report will be send by something like (using libusb): 
`libusb_control_transfer(dev, CTRL_OUT, HID_SET_REPORT,(HID_REPORT_TYPE_FEATURE<<8)|0x00, 0, pkt, len, TIMEOUT);`

**Comment by NicoHood** [comment]
This is not a support forum. Please go the normal way to contact me:
contact.nicohood.de
