### ISSUE TITLE
Report descriptor longer than 256 bytes?

### ISSUE THREAD

**Issue by Razyre** [NicoHood/HID#95]
Hi there. I'm implementing a rather large report descriptor for a power HID USB device. I'm actually using the Teensy version of the library at the moment, but wondered if I could achieve this with yours.

My descriptor is around 800 bytes long with 11 parts to the report, I haven't really even verified if it's possible to do multiple report IDs with these libraries yet though I assume it is. Essentially, the device throws an error when connected and when I inspect the packets that arrive at the PC, if I set the size of the descriptor to say 900, unsurprisingly the 8 bit integer array which contains descriptor information has overflowed and displays as 132 bytes, cutting most of the descriptor off.

I very much doubt bulk changing everything to 16 bit integers is going to help me because I would guess there's some maths involved that involves the 8 bit variables integral to the library. 

I apologise if this isn't the appropriate place to post and sorry for my lack of knowledge, I'm very new to USB and HID and I'm learning as fast as I can.

If there is any way of fixing this issue I'd love to know :)

Thanks

**Comment by NicoHood** [comment]
This is not a support forum, I am sorry. Please ask via gpg mail or tox again and I am happy to answer you all your questions.
contact.nicohood.de
